version: "3"

services:
  # api:
  #   container_name: django_rest_api
  #   build:
  #     context: .
  #     dockerfile: DockerfilePython
  #   volumes:
  #     - ./:/app/
  #   tty: true
  #   ports:
  #     - 8000:8000
  web_front:
    container_name: django_web_front
    build:
      context: .
      dockerfile: DockerfileNode
    volumes:
      - ./frontend:/django_web_front
    tty: true
    command: sh -c "npm install && npm run start"
    ports:
      - 3000:3000
        #  depends_on:
        #    - api

volumes:
  django_data_volume:
