version: "3"

services:
  api:
    container_name: django_rest_api
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    working_dir: /app
    build:
      context: .
      dockerfile: DockerfilePython
    tty: true
    ports:
      - 8000:8000
  web_front:
    container_name: django_web_front
    build:
      context: .
      dockerfile: DockerfileNode
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - api

